### ISSUE TITLE
followup to #1

### ISSUE THREAD

**Issue by gregbo** [jhaas-pfrc/draft-haas-idr-bgp-attribute-escape#2]
There are some sentences in which the subject and verb don't agree.  For example, in the "Escape" section, the second paragraph starts with "A first example of escape are Path Attributes ..."  I could make some suggestions, or wait for the RFC Editor's feedback (if any).

Also, in the "Escape" section, I wasn't sure what you meant by "That is, the feature intra-AS only."  (Did you mean "That is, the feature is only applicable intra-AS" or words to that effect?

If you're planning to take this draft (and its presentation) "on the road" as you suggested at IETF 117, I'd suggest RIPE also, as they have encountered [similar issues](https://labs.ripe.net/author/berislav_todorovic/bgp-path-attribute-filtering-a-powerful-tool-to-mitigate-alien-attributes/).

**Comment by jhaas-pfrc** [comment]
The English in the document was certainly in need of improvement.  If you can take a moment to review the associated pull request and the remainder of the document, I would appreciate it.

My hope is to try to push the update by end of week to the datatracker.
